//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/EtVK/Scrips/Input Module/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""87e294db-7992-4ef0-890a-79f9d59f8e45"",
            ""actions"": [
                {
                    ""name"": ""MouseLook"",
                    ""type"": ""PassThrough"",
                    ""id"": ""09b60f17-682a-4d87-bae5-b41ba8db7f81"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1fe8d2f1-da7b-42da-bca7-f0a11ff59cb5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapJump"",
                    ""type"": ""Button"",
                    ""id"": ""defdbe6a-e18a-447a-b578-4bb60b5f56d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldRun"",
                    ""type"": ""Button"",
                    ""id"": ""3ae03cf3-45a2-4f65-9baf-fc1fa9880bd5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapRun"",
                    ""type"": ""Button"",
                    ""id"": ""42ae9469-3ba9-4923-bbfe-dc7cfd903a21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StateSwitch"",
                    ""type"": ""Button"",
                    ""id"": ""2a7bd285-2981-469e-a336-baa46b24e1a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldAttack"",
                    ""type"": ""Button"",
                    ""id"": ""0483dbb4-f09d-4c49-909e-e3a6d9b87c9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.3)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapAttack"",
                    ""type"": ""Button"",
                    ""id"": ""97444c1a-0b58-4815-bb67-6d32edd8593c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HoldAim"",
                    ""type"": ""Button"",
                    ""id"": ""7dc4422f-cc2d-4ed5-aba1-e6270177be2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapAim"",
                    ""type"": ""Button"",
                    ""id"": ""05f71b4e-b8f3-4771-bb75-adfc8d5463e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.15)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon_1"",
                    ""type"": ""Button"",
                    ""id"": ""a7382717-7efb-411c-bfdc-b392576b1957"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TapInteract"",
                    ""type"": ""Button"",
                    ""id"": ""ea2b83c4-5f0d-47e0-b50c-6f6ab0849fc4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon_3"",
                    ""type"": ""Button"",
                    ""id"": ""a6a5db7a-123c-4673-a9f7-2aa954ea66b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon_2"",
                    ""type"": ""Button"",
                    ""id"": ""487fd9eb-59f6-4955-a055-352e23772c8e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""c45607a6-5c45-472e-be77-62d08631e286"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""37e8bf7e-caee-47f5-82c4-92e22335aefd"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a5cbcbb8-a35e-4f97-9872-6b44661cc42e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5e0ba8f3-f1d2-42a5-b826-aaf39e91d6c8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""838df48c-3be4-4b0a-a656-2f329162bed3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""029f8d5d-39e7-468f-8f04-a841dfa5cc2d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""53d066c5-eb7d-4d4e-993e-114216c86933"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6ff96cf7-be32-4e31-8369-eff300b6a828"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81627c7b-f3ad-4c20-9f56-f2b3b7152de6"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90bac4f8-373f-4208-b6c1-705c15347e9d"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StateSwitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c141b89-efb0-45d5-838c-454f98be5512"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2e2c765-877c-40f6-8b86-12c3463f0c13"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapRun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da6f7cc3-7899-4021-8ef4-a1e4f571ce6b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5040e177-d4d5-46e2-9f29-50043ccbe55a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HoldAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fb030a7-a603-44f1-a64a-a9366cedc31a"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapAim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4271136e-06e0-4538-8ff3-1d346eb56540"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39d4ba95-9c89-4889-ae3b-a97409854442"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TapInteract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a29a5cc-bc7e-477b-824c-b519c142df92"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee768bbf-d6b1-4c61-95cc-f38fed983730"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0073111a-2398-497a-9c97-48bdf2ac873a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""ce3675b6-d9b7-4e60-848c-1a037743b091"",
            ""actions"": [
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""5ed3c56f-3b43-46f5-bee4-ec29f1dbc6e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.25)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""329672c3-79cf-4107-8c3e-aab06699f8ae"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_MouseLook = m_Player.FindAction("MouseLook", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_TapJump = m_Player.FindAction("TapJump", throwIfNotFound: true);
        m_Player_HoldRun = m_Player.FindAction("HoldRun", throwIfNotFound: true);
        m_Player_TapRun = m_Player.FindAction("TapRun", throwIfNotFound: true);
        m_Player_StateSwitch = m_Player.FindAction("StateSwitch", throwIfNotFound: true);
        m_Player_HoldAttack = m_Player.FindAction("HoldAttack", throwIfNotFound: true);
        m_Player_TapAttack = m_Player.FindAction("TapAttack", throwIfNotFound: true);
        m_Player_HoldAim = m_Player.FindAction("HoldAim", throwIfNotFound: true);
        m_Player_TapAim = m_Player.FindAction("TapAim", throwIfNotFound: true);
        m_Player_Weapon_1 = m_Player.FindAction("Weapon_1", throwIfNotFound: true);
        m_Player_TapInteract = m_Player.FindAction("TapInteract", throwIfNotFound: true);
        m_Player_Weapon_3 = m_Player.FindAction("Weapon_3", throwIfNotFound: true);
        m_Player_Weapon_2 = m_Player.FindAction("Weapon_2", throwIfNotFound: true);
        m_Player_Escape = m_Player.FindAction("Escape", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Escape = m_UI.FindAction("Escape", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_MouseLook;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_TapJump;
    private readonly InputAction m_Player_HoldRun;
    private readonly InputAction m_Player_TapRun;
    private readonly InputAction m_Player_StateSwitch;
    private readonly InputAction m_Player_HoldAttack;
    private readonly InputAction m_Player_TapAttack;
    private readonly InputAction m_Player_HoldAim;
    private readonly InputAction m_Player_TapAim;
    private readonly InputAction m_Player_Weapon_1;
    private readonly InputAction m_Player_TapInteract;
    private readonly InputAction m_Player_Weapon_3;
    private readonly InputAction m_Player_Weapon_2;
    private readonly InputAction m_Player_Escape;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MouseLook => m_Wrapper.m_Player_MouseLook;
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @TapJump => m_Wrapper.m_Player_TapJump;
        public InputAction @HoldRun => m_Wrapper.m_Player_HoldRun;
        public InputAction @TapRun => m_Wrapper.m_Player_TapRun;
        public InputAction @StateSwitch => m_Wrapper.m_Player_StateSwitch;
        public InputAction @HoldAttack => m_Wrapper.m_Player_HoldAttack;
        public InputAction @TapAttack => m_Wrapper.m_Player_TapAttack;
        public InputAction @HoldAim => m_Wrapper.m_Player_HoldAim;
        public InputAction @TapAim => m_Wrapper.m_Player_TapAim;
        public InputAction @Weapon_1 => m_Wrapper.m_Player_Weapon_1;
        public InputAction @TapInteract => m_Wrapper.m_Player_TapInteract;
        public InputAction @Weapon_3 => m_Wrapper.m_Player_Weapon_3;
        public InputAction @Weapon_2 => m_Wrapper.m_Player_Weapon_2;
        public InputAction @Escape => m_Wrapper.m_Player_Escape;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @MouseLook.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseLook;
                @MouseLook.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseLook;
                @MouseLook.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseLook;
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @TapJump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapJump;
                @TapJump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapJump;
                @TapJump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapJump;
                @HoldRun.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldRun;
                @HoldRun.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldRun;
                @HoldRun.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldRun;
                @TapRun.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapRun;
                @TapRun.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapRun;
                @TapRun.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapRun;
                @StateSwitch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStateSwitch;
                @StateSwitch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStateSwitch;
                @StateSwitch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStateSwitch;
                @HoldAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                @HoldAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                @HoldAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAttack;
                @TapAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapAttack;
                @TapAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapAttack;
                @TapAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapAttack;
                @HoldAim.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAim;
                @HoldAim.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAim;
                @HoldAim.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHoldAim;
                @TapAim.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapAim;
                @TapAim.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapAim;
                @TapAim.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapAim;
                @Weapon_1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_1;
                @Weapon_1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_1;
                @Weapon_1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_1;
                @TapInteract.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapInteract;
                @TapInteract.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapInteract;
                @TapInteract.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTapInteract;
                @Weapon_3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_3;
                @Weapon_3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_3;
                @Weapon_3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_3;
                @Weapon_2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_2;
                @Weapon_2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_2;
                @Weapon_2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWeapon_2;
                @Escape.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MouseLook.started += instance.OnMouseLook;
                @MouseLook.performed += instance.OnMouseLook;
                @MouseLook.canceled += instance.OnMouseLook;
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @TapJump.started += instance.OnTapJump;
                @TapJump.performed += instance.OnTapJump;
                @TapJump.canceled += instance.OnTapJump;
                @HoldRun.started += instance.OnHoldRun;
                @HoldRun.performed += instance.OnHoldRun;
                @HoldRun.canceled += instance.OnHoldRun;
                @TapRun.started += instance.OnTapRun;
                @TapRun.performed += instance.OnTapRun;
                @TapRun.canceled += instance.OnTapRun;
                @StateSwitch.started += instance.OnStateSwitch;
                @StateSwitch.performed += instance.OnStateSwitch;
                @StateSwitch.canceled += instance.OnStateSwitch;
                @HoldAttack.started += instance.OnHoldAttack;
                @HoldAttack.performed += instance.OnHoldAttack;
                @HoldAttack.canceled += instance.OnHoldAttack;
                @TapAttack.started += instance.OnTapAttack;
                @TapAttack.performed += instance.OnTapAttack;
                @TapAttack.canceled += instance.OnTapAttack;
                @HoldAim.started += instance.OnHoldAim;
                @HoldAim.performed += instance.OnHoldAim;
                @HoldAim.canceled += instance.OnHoldAim;
                @TapAim.started += instance.OnTapAim;
                @TapAim.performed += instance.OnTapAim;
                @TapAim.canceled += instance.OnTapAim;
                @Weapon_1.started += instance.OnWeapon_1;
                @Weapon_1.performed += instance.OnWeapon_1;
                @Weapon_1.canceled += instance.OnWeapon_1;
                @TapInteract.started += instance.OnTapInteract;
                @TapInteract.performed += instance.OnTapInteract;
                @TapInteract.canceled += instance.OnTapInteract;
                @Weapon_3.started += instance.OnWeapon_3;
                @Weapon_3.performed += instance.OnWeapon_3;
                @Weapon_3.canceled += instance.OnWeapon_3;
                @Weapon_2.started += instance.OnWeapon_2;
                @Weapon_2.performed += instance.OnWeapon_2;
                @Weapon_2.canceled += instance.OnWeapon_2;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Escape;
    public struct UIActions
    {
        private @PlayerInputActions m_Wrapper;
        public UIActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Escape => m_Wrapper.m_UI_Escape;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Escape.started -= m_Wrapper.m_UIActionsCallbackInterface.OnEscape;
                @Escape.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnEscape;
                @Escape.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnEscape;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IPlayerActions
    {
        void OnMouseLook(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnTapJump(InputAction.CallbackContext context);
        void OnHoldRun(InputAction.CallbackContext context);
        void OnTapRun(InputAction.CallbackContext context);
        void OnStateSwitch(InputAction.CallbackContext context);
        void OnHoldAttack(InputAction.CallbackContext context);
        void OnTapAttack(InputAction.CallbackContext context);
        void OnHoldAim(InputAction.CallbackContext context);
        void OnTapAim(InputAction.CallbackContext context);
        void OnWeapon_1(InputAction.CallbackContext context);
        void OnTapInteract(InputAction.CallbackContext context);
        void OnWeapon_3(InputAction.CallbackContext context);
        void OnWeapon_2(InputAction.CallbackContext context);
        void OnEscape(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnEscape(InputAction.CallbackContext context);
    }
}
